/**
 * AZAVISION — Admin ERP i18n (FR · PT · EN · ES)
 */
(function (global) {
  'use strict';

  var L = {
    fr: {
      appTitle: 'AZAVISION Admin',
      loginTitle: 'Connexion administrateur',
      email: 'E-mail', password: 'Mot de passe', loginBtn: 'Se connecter',
      logout: 'Déconnexion', loading: 'Chargement…', save: 'Enregistrer', cancel: 'Annuler',
      delete: 'Supprimer', edit: 'Modifier', add: 'Ajouter', back: 'Retour', search: 'Rechercher',
      noData: 'Aucune donnée', saved: 'Enregistré', error: 'Erreur', connected: 'Connecté',
      sessionExpired: 'Session expirée — reconnectez-vous',
      nav: { dashboard: 'Tableau de bord', products: 'Produits', categories: 'Catégories', orders: 'Commandes', clients: 'Clients', config: 'Boutique', coupons: 'Promotions', promotions: 'Promotions', more: 'Plus' },
      dash: { title: 'Tableau de bord', clients: 'Clients', products: 'Produits actifs', orders: 'Commandes', revenue: 'Revenu total', today: 'Ventes aujourd\'hui', pending: 'Commandes en attente', stockAlerts: 'Alertes stock', recentOrders: 'Commandes récentes' },
      prod: { title: 'Produits', new: 'Nouveau produit', name: 'Nom', desc: 'Description', category: 'Catégorie', priceHt: 'Prix HT (€)', tva: 'TVA (%)', image: 'URL image', catalogStatus: 'Visibilité vitrine', statusDraft: 'Brouillon', statusPublished: 'Publié', statusScheduled: 'Programmé', stock: 'Gérer le stock', deliveryDays: 'Délai livraison (jours)', size: 'Taille', color: 'Couleur', qty: 'Stock', trash: 'Corbeille', active: 'Tous', all: 'Tous', published: 'Publiés', scheduled: 'Programmés', draft: 'Brouillons', confirmDelete: 'Mettre ce produit à la corbeille ?', confirmRestore: 'Restaurer ce produit depuis la corbeille ?', confirmPurge: 'Supprimer définitivement ce produit ? Cette action est irréversible.', restore: 'Restaurer', purge: 'Supprimer définitivement', duplicate: 'Dupliquer', publishNow: 'Publier', toDraft: 'Brouillon', publishAt: 'Date de publication', stockTotal: 'Stock', variants: 'Variantes', selected: 'sélectionné(s)', bulkPublish: 'Publier la sélection', bulkDraft: 'Mettre en brouillon', bulkTrash: 'Mettre à la corbeille', bulkRestore: 'Restaurer la sélection', bulkPurge: 'Supprimer définitivement', id: 'Réf.' },
      cat: { title: 'Catégories', new: 'Nouvelle catégorie', name: 'Nom', desc: 'Description', status: 'Statut vitrine', published: 'Publié', draft: 'Masqué' },
      ord: { title: 'Commandes', id: 'N° commande', date: 'Date', client: 'Client', total: 'Total', status: 'Statut', pay: 'Paiement', ship: 'Livraison', detail: 'Détail commande', items: 'Articles', tracking: 'N° suivi', carrier: 'Transporteur', updateStatus: 'Mettre à jour', notes: 'Notes internes', filterAll: 'Tous', filterPending: 'En attente', filterPaid: 'Payées', filterShipped: 'Expédiées', exportCsv: 'Exporter CSV' },
      cli: { title: 'Clients', name: 'Nom', email: 'E-mail', phone: 'Téléphone', since: 'Inscrit le' },
      cfg: { title: 'Configuration vitrine', subtitle: 'Ces réglages alimentent la boutique client (01-vitrine-client).', shipping: 'Livraison', freeFrom: 'Livraison gratuite dès (€)', flatRate: 'Frais de port (€)', payments: 'Paiements', stripe: 'Stripe activé', cod: 'Paiement à la livraison', showStripe: 'Afficher Stripe', showCod: 'Afficher paiement à la livraison', showTransfer: 'Afficher virement', promo: 'Bandeau promo', promoText: 'Texte du bandeau', promoOn: 'Bandeau activé', contact: 'Contact', storeEmail: 'E-mail boutique', publicEmail: 'E-mail affiché (contact)', whatsapp: 'WhatsApp (numéro ou lien)', lang: 'Langue par défaut vitrine' },
      cup: { title: 'Codes promo', code: 'Code', type: 'Type', value: 'Valeur', percent: 'Pourcentage', fixed: 'Montant fixe', freeShip: 'Livraison gratuite', active: 'Actifs', inactive: 'Inactifs', new: 'Nouveau code', edit: 'Modifier le code', desc: 'Description', startDate: 'Date début', endDate: 'Date fin', usage: 'Utilisations', maxUsage: 'Limite d\'utilisation', status: 'Statut', confirmDelete: 'Désactiver ce code promo ?' },
      promo: { title: 'Promotions', couponsTab: 'Codes promo', bannerTab: 'Bandeau vitrine', bannerDesc: 'Texte affiché en haut de la boutique client.', bannerText: 'Texte du bandeau', bannerOn: 'Bandeau activé', saveBanner: 'Enregistrer le bandeau' },
      wiz: { subtitle: 'Images organisées dans Google Drive (catégorie → produit). Variantes taille × couleur enregistrées dans Sheets.', syncDrive: 'Sync Drive', imageSection: 'Image produit', clickUpload: 'Cliquez pour télécharger', dragDrop: 'ou glissez une image', clearImage: 'Retirer', orUrl: 'Ou URL image', infoSection: 'Informations', perVariant: 'par variante', sizes: 'Tailles disponibles', colors: 'Couleurs disponibles', colorName: 'Nom couleur', addColor: 'Ajouter', driveGallery: 'Galerie Drive', driveHint: 'Images déjà présentes dans ERP_Boutique_Images — cliquez pour réutiliser.', previewTitle: 'Aperçu en direct', previewEmpty: 'Aperçu image', previewName: 'Nom du produit', variants: 'variantes', driveStructure: 'Organisation Drive', syncing: 'Synchronisation Drive…', syncOk: 'Dossiers Drive synchronisés', noDriveImages: 'Aucune image dans Drive', nameRequired: 'Nom requis', catRequired: 'Catégorie requise', sizeRequired: 'Sélectionnez au moins une taille', colorRequired: 'Sélectionnez au moins une couleur', imgRequired: 'Ajoutez une image', imgTypeError: 'Fichier image invalide', imgSizeError: 'Image trop volumineuse (max 6 Mo)', uploadError: 'Échec upload Drive' },
      apiBanner: 'Configurez l\'URL API en bas de <code>index.html</code> (même URL que la vitrine).'
    },
    pt: {
      appTitle: 'AZAVISION Admin',
      loginTitle: 'Entrada de administrador',
      email: 'E-mail', password: 'Palavra-passe', loginBtn: 'Entrar',
      logout: 'Terminar sessão', loading: 'A carregar…', save: 'Guardar', cancel: 'Cancelar',
      delete: 'Eliminar', edit: 'Editar', add: 'Adicionar', back: 'Voltar', search: 'Pesquisar',
      noData: 'Sem dados', saved: 'Guardado', error: 'Erro', connected: 'Sessão iniciada',
      sessionExpired: 'Sessão expirada — volte a entrar',
      nav: { dashboard: 'Painel', products: 'Produtos', categories: 'Categorias', orders: 'Encomendas', clients: 'Clientes', config: 'Loja', coupons: 'Promoções', promotions: 'Promoções', more: 'Mais' },
      dash: { title: 'Painel', clients: 'Clientes', products: 'Produtos ativos', orders: 'Encomendas', revenue: 'Receita total', today: 'Vendas hoje', pending: 'Encomendas pendentes', stockAlerts: 'Alertas stock', recentOrders: 'Encomendas recentes' },
      prod: { title: 'Produtos', new: 'Novo produto', name: 'Nome', desc: 'Descrição', category: 'Categoria', priceHt: 'Preço s/ IVA (€)', tva: 'IVA (%)', image: 'URL imagem', catalogStatus: 'Visibilidade loja', statusDraft: 'Rascunho', statusPublished: 'Publicado', statusScheduled: 'Agendado', stock: 'Gerir stock', deliveryDays: 'Prazo entrega (dias)', size: 'Tamanho', color: 'Cor', qty: 'Stock', trash: 'Lixo', active: 'Todos', all: 'Todos', published: 'Publicados', scheduled: 'Agendados', draft: 'Rascunhos', confirmDelete: 'Mover este produto para o lixo?', confirmRestore: 'Restaurar este produto do lixo?', confirmPurge: 'Eliminar definitivamente? Ação irreversível.', restore: 'Restaurar', purge: 'Eliminar definitivamente', duplicate: 'Duplicar', publishNow: 'Publicar', toDraft: 'Rascunho', publishAt: 'Data de publicação', stockTotal: 'Stock', variants: 'Variantes', selected: 'selecionado(s)', bulkPublish: 'Publicar seleção', bulkDraft: 'Rascunho', bulkTrash: 'Para o lixo', bulkRestore: 'Restaurar seleção', bulkPurge: 'Eliminar definitivamente', id: 'Ref.' },
      cat: { title: 'Categorias', new: 'Nova categoria', name: 'Nome', desc: 'Descrição', status: 'Estado na loja', published: 'Publicado', draft: 'Oculto' },
      ord: { title: 'Encomendas', id: 'N.º encomenda', date: 'Data', client: 'Cliente', total: 'Total', status: 'Estado', pay: 'Pagamento', ship: 'Envio', detail: 'Detalhe', items: 'Artigos', tracking: 'N.º rastreio', carrier: 'Transportadora', updateStatus: 'Atualizar', notes: 'Notas internas', filterAll: 'Todas', filterPending: 'Pendentes', filterPaid: 'Pagas', filterShipped: 'Enviadas', exportCsv: 'Exportar CSV' },
      cli: { title: 'Clientes', name: 'Nome', email: 'E-mail', phone: 'Telefone', since: 'Registo' },
      cfg: { title: 'Configuração da loja', subtitle: 'Estes valores alimentam a vitrine (01-vitrine-client).', shipping: 'Envio', freeFrom: 'Envio grátis a partir de (€)', flatRate: 'Portes (€)', payments: 'Pagamentos', stripe: 'Stripe ativo', cod: 'Pagamento à entrega', showStripe: 'Mostrar Stripe', showCod: 'Mostrar contra-reembolso', showTransfer: 'Mostrar transferência', promo: 'Faixa promocional', promoText: 'Texto da faixa', promoOn: 'Faixa ativa', contact: 'Contacto', storeEmail: 'E-mail loja', publicEmail: 'E-mail público', whatsapp: 'WhatsApp', lang: 'Idioma predefinido' },
      cup: { title: 'Cupões', code: 'Código', type: 'Tipo', value: 'Valor', percent: 'Percentagem', fixed: 'Valor fixo', freeShip: 'Envio grátis', active: 'Ativos', inactive: 'Inativos', new: 'Novo cupão', edit: 'Editar cupão', desc: 'Descrição', startDate: 'Data início', endDate: 'Data fim', usage: 'Utilizações', maxUsage: 'Limite', status: 'Estado', confirmDelete: 'Desativar este cupão?' },
      promo: { title: 'Promoções', couponsTab: 'Cupões', bannerTab: 'Faixa da loja', bannerDesc: 'Texto no topo da vitrine cliente.', bannerText: 'Texto da faixa', bannerOn: 'Faixa ativa', saveBanner: 'Guardar faixa' },
      wiz: { subtitle: 'Imagens organizadas no Google Drive (categoria → produto). Variantes tamanho × cor guardadas no Sheets.', syncDrive: 'Sync Drive', imageSection: 'Imagem produto', clickUpload: 'Clique para carregar', dragDrop: 'ou arraste uma imagem', clearImage: 'Remover', orUrl: 'Ou URL imagem', infoSection: 'Informações', perVariant: 'por variante', sizes: 'Tamanhos disponíveis', colors: 'Cores disponíveis', colorName: 'Nome cor', addColor: 'Adicionar', driveGallery: 'Galeria Drive', driveHint: 'Imagens já em ERP_Boutique_Images — clique para reutilizar.', previewTitle: 'Pré-visualização', previewEmpty: 'Pré-visualização', previewName: 'Nome do produto', variants: 'variantes', driveStructure: 'Organização Drive', syncing: 'A sincronizar Drive…', syncOk: 'Pastas Drive sincronizadas', noDriveImages: 'Sem imagens no Drive', nameRequired: 'Nome obrigatório', catRequired: 'Categoria obrigatória', sizeRequired: 'Selecione pelo menos um tamanho', colorRequired: 'Selecione pelo menos uma cor', imgRequired: 'Adicione uma imagem', imgTypeError: 'Ficheiro inválido', imgSizeError: 'Imagem demasiado grande (máx. 6 Mo)', uploadError: 'Falha no upload Drive' },
      apiBanner: 'Configure o URL da API no final do <code>index.html</code> (o mesmo da vitrine).'
    },
    en: {
      appTitle: 'AZAVISION Admin',
      loginTitle: 'Administrator sign in',
      email: 'Email', password: 'Password', loginBtn: 'Sign in',
      logout: 'Sign out', loading: 'Loading…', save: 'Save', cancel: 'Cancel',
      delete: 'Delete', edit: 'Edit', add: 'Add', back: 'Back', search: 'Search',
      noData: 'No data', saved: 'Saved', error: 'Error', connected: 'Signed in',
      sessionExpired: 'Session expired — please sign in again',
      nav: { dashboard: 'Dashboard', products: 'Products', categories: 'Categories', orders: 'Orders', clients: 'Clients', config: 'Storefront', coupons: 'Promotions', promotions: 'Promotions', more: 'More' },
      dash: { title: 'Dashboard', clients: 'Clients', products: 'Active products', orders: 'Orders', revenue: 'Total revenue', today: 'Sales today', pending: 'Pending orders', stockAlerts: 'Stock alerts', recentOrders: 'Recent orders' },
      prod: { title: 'Products', new: 'New product', name: 'Name', desc: 'Description', category: 'Category', priceHt: 'Price ex. VAT (€)', tva: 'VAT (%)', image: 'Image URL', catalogStatus: 'Store visibility', statusDraft: 'Draft', statusPublished: 'Published', statusScheduled: 'Scheduled', stock: 'Manage stock', deliveryDays: 'Lead time (days)', size: 'Size', color: 'Color', qty: 'Stock', trash: 'Trash', active: 'All', all: 'All', published: 'Published', scheduled: 'Scheduled', draft: 'Drafts', confirmDelete: 'Move this product to trash?', confirmRestore: 'Restore from trash?', confirmPurge: 'Permanently delete? Cannot be undone.', restore: 'Restore', purge: 'Delete permanently', duplicate: 'Duplicate', publishNow: 'Publish', toDraft: 'Draft', publishAt: 'Publish date', stockTotal: 'Stock', variants: 'Variants', selected: 'selected', bulkPublish: 'Publish selected', bulkDraft: 'Set draft', bulkTrash: 'Move to trash', bulkRestore: 'Restore selected', bulkPurge: 'Delete permanently', id: 'Ref.' },
      cat: { title: 'Categories', new: 'New category', name: 'Name', desc: 'Description', status: 'Store status', published: 'Published', draft: 'Hidden' },
      ord: { title: 'Orders', id: 'Order #', date: 'Date', client: 'Customer', total: 'Total', status: 'Status', pay: 'Payment', ship: 'Shipping', detail: 'Order detail', items: 'Items', tracking: 'Tracking #', carrier: 'Carrier', updateStatus: 'Update', notes: 'Internal notes', filterAll: 'All', filterPending: 'Pending', filterPaid: 'Paid', filterShipped: 'Shipped', exportCsv: 'Export CSV' },
      cli: { title: 'Customers', name: 'Name', email: 'Email', phone: 'Phone', since: 'Registered' },
      cfg: { title: 'Storefront settings', subtitle: 'These values power the client shop (01-vitrine-client).', shipping: 'Shipping', freeFrom: 'Free shipping from (€)', flatRate: 'Flat rate (€)', payments: 'Payments', stripe: 'Stripe enabled', cod: 'Cash on delivery', showStripe: 'Show Stripe', showCod: 'Show COD', showTransfer: 'Show bank transfer', promo: 'Promo bar', promoText: 'Bar text', promoOn: 'Bar enabled', contact: 'Contact', storeEmail: 'Store email', publicEmail: 'Public contact email', whatsapp: 'WhatsApp', lang: 'Default language' },
      cup: { title: 'Coupon codes', code: 'Code', type: 'Type', value: 'Value', percent: 'Percent', fixed: 'Fixed amount', freeShip: 'Free shipping', active: 'Active', inactive: 'Inactive', new: 'New coupon', edit: 'Edit coupon', desc: 'Description', startDate: 'Start date', endDate: 'End date', usage: 'Uses', maxUsage: 'Usage limit', status: 'Status', confirmDelete: 'Deactivate this coupon?' },
      promo: { title: 'Promotions', couponsTab: 'Coupon codes', bannerTab: 'Storefront banner', bannerDesc: 'Text at the top of the client shop.', bannerText: 'Banner text', bannerOn: 'Banner enabled', saveBanner: 'Save banner' },
      wiz: { subtitle: 'Images organized in Google Drive (category → product). Size × color variants saved to Sheets.', syncDrive: 'Sync Drive', imageSection: 'Product image', clickUpload: 'Click to upload', dragDrop: 'or drag an image', clearImage: 'Remove', orUrl: 'Or image URL', infoSection: 'Details', perVariant: 'per variant', sizes: 'Available sizes', colors: 'Available colors', colorName: 'Color name', addColor: 'Add', driveGallery: 'Drive gallery', driveHint: 'Images already in ERP_Boutique_Images — click to reuse.', previewTitle: 'Live preview', previewEmpty: 'Image preview', previewName: 'Product name', variants: 'variants', driveStructure: 'Drive structure', syncing: 'Syncing Drive…', syncOk: 'Drive folders synced', noDriveImages: 'No images in Drive', nameRequired: 'Name required', catRequired: 'Category required', sizeRequired: 'Select at least one size', colorRequired: 'Select at least one color', imgRequired: 'Add an image', imgTypeError: 'Invalid image file', imgSizeError: 'Image too large (max 6 MB)', uploadError: 'Drive upload failed' },
      apiBanner: 'Set the API URL at the bottom of <code>index.html</code> (same as the storefront).'
    },
    es: {
      appTitle: 'AZAVISION Admin',
      loginTitle: 'Acceso administrador',
      email: 'Correo', password: 'Contraseña', loginBtn: 'Iniciar sesión',
      logout: 'Cerrar sesión', loading: 'Cargando…', save: 'Guardar', cancel: 'Cancelar',
      delete: 'Eliminar', edit: 'Editar', add: 'Añadir', back: 'Volver', search: 'Buscar',
      noData: 'Sin datos', saved: 'Guardado', error: 'Error', connected: 'Sesión iniciada',
      sessionExpired: 'Sesión caducada — vuelva a iniciar sesión',
      nav: { dashboard: 'Panel', products: 'Productos', categories: 'Categorías', orders: 'Pedidos', clients: 'Clientes', config: 'Tienda', coupons: 'Promociones', promotions: 'Promociones', more: 'Más' },
      dash: { title: 'Panel', clients: 'Clientes', products: 'Productos activos', orders: 'Pedidos', revenue: 'Ingresos totales', today: 'Ventas hoy', pending: 'Pedidos pendientes', stockAlerts: 'Alertas stock', recentOrders: 'Pedidos recientes' },
      prod: { title: 'Productos', new: 'Nuevo producto', name: 'Nombre', desc: 'Descripción', category: 'Categoría', priceHt: 'Precio sin IVA (€)', tva: 'IVA (%)', image: 'URL imagen', catalogStatus: 'Visibilidad tienda', statusDraft: 'Borrador', statusPublished: 'Publicado', statusScheduled: 'Programado', stock: 'Gestionar stock', deliveryDays: 'Plazo entrega (días)', size: 'Talla', color: 'Color', qty: 'Stock', trash: 'Papelera', active: 'Todos', all: 'Todos', published: 'Publicados', scheduled: 'Programados', draft: 'Borradores', confirmDelete: '¿Mover a la papelera?', confirmRestore: '¿Restaurar de la papelera?', confirmPurge: '¿Eliminar definitivamente?', restore: 'Restaurar', purge: 'Eliminar definitivamente', duplicate: 'Duplicar', publishNow: 'Publicar', toDraft: 'Borrador', publishAt: 'Fecha de publicación', stockTotal: 'Stock', variants: 'Variantes', selected: 'seleccionado(s)', bulkPublish: 'Publicar selección', bulkDraft: 'Borrador', bulkTrash: 'A la papelera', bulkRestore: 'Restaurar selección', bulkPurge: 'Eliminar definitivamente', id: 'Ref.' },
      cat: { title: 'Categorías', new: 'Nueva categoría', name: 'Nombre', desc: 'Descripción', status: 'Estado en tienda', published: 'Publicado', draft: 'Oculto' },
      ord: { title: 'Pedidos', id: 'N.º pedido', date: 'Fecha', client: 'Cliente', total: 'Total', status: 'Estado', pay: 'Pago', ship: 'Envío', detail: 'Detalle', items: 'Artículos', tracking: 'N.º seguimiento', carrier: 'Transportista', updateStatus: 'Actualizar', notes: 'Notas internas', filterAll: 'Todos', filterPending: 'Pendientes', filterPaid: 'Pagados', filterShipped: 'Enviados', exportCsv: 'Exportar CSV' },
      cli: { title: 'Clientes', name: 'Nombre', email: 'Correo', phone: 'Teléfono', since: 'Registro' },
      cfg: { title: 'Configuración tienda', subtitle: 'Estos valores alimentan la vitrina (01-vitrine-client).', shipping: 'Envío', freeFrom: 'Envío gratis desde (€)', flatRate: 'Gastos envío (€)', payments: 'Pagos', stripe: 'Stripe activo', cod: 'Contra reembolso', showStripe: 'Mostrar Stripe', showCod: 'Mostrar contra reembolso', showTransfer: 'Mostrar transferencia', promo: 'Banda promocional', promoText: 'Texto banda', promoOn: 'Banda activa', contact: 'Contacto', storeEmail: 'Correo tienda', publicEmail: 'Correo público', whatsapp: 'WhatsApp', lang: 'Idioma por defecto' },
      cup: { title: 'Cupones', code: 'Código', type: 'Tipo', value: 'Valor', percent: 'Porcentaje', fixed: 'Importe fijo', freeShip: 'Envío gratis', active: 'Activos', inactive: 'Inactivos', new: 'Nuevo cupón', edit: 'Editar cupón', desc: 'Descripción', startDate: 'Fecha inicio', endDate: 'Fecha fin', usage: 'Usos', maxUsage: 'Límite', status: 'Estado', confirmDelete: '¿Desactivar este cupón?' },
      promo: { title: 'Promociones', couponsTab: 'Cupones', bannerTab: 'Banda vitrina', bannerDesc: 'Texto en la parte superior de la tienda.', bannerText: 'Texto de la banda', bannerOn: 'Banda activa', saveBanner: 'Guardar banda' },
      wiz: { subtitle: 'Imágenes organizadas en Google Drive (categoría → producto). Variantes talla × color en Sheets.', syncDrive: 'Sync Drive', imageSection: 'Imagen producto', clickUpload: 'Clic para subir', dragDrop: 'o arrastre una imagen', clearImage: 'Quitar', orUrl: 'O URL imagen', infoSection: 'Información', perVariant: 'por variante', sizes: 'Tallas disponibles', colors: 'Colores disponibles', colorName: 'Nombre color', addColor: 'Añadir', driveGallery: 'Galería Drive', driveHint: 'Imágenes en ERP_Boutique_Images — clic para reutilizar.', previewTitle: 'Vista previa', previewEmpty: 'Vista previa', previewName: 'Nombre producto', variants: 'variantes', driveStructure: 'Organización Drive', syncing: 'Sincronizando Drive…', syncOk: 'Carpetas Drive sincronizadas', noDriveImages: 'Sin imágenes en Drive', nameRequired: 'Nombre obligatorio', catRequired: 'Categoría obligatoria', sizeRequired: 'Seleccione al menos una talla', colorRequired: 'Seleccione al menos un color', imgRequired: 'Añada una imagen', imgTypeError: 'Archivo inválido', imgSizeError: 'Imagen demasiado grande (máx. 6 Mo)', uploadError: 'Error al subir a Drive' },
      apiBanner: 'Configure la URL API al final de <code>index.html</code> (la misma que la vitrina).'
    }
  };

  global.AdminI18n = L;
  global.AdminT = {};
  ['fr', 'pt', 'en', 'es'].forEach(function (code) {
    global.AdminT[code] = L[code];
  });
})(typeof window !== 'undefined' ? window : this);
